### ISSUE TITLE
Add Caffe examples

### ISSUE THREAD

**Issue by ressy** [eng-it/grid-tests#2]
We should add example Caffe jobs, including using its CUDA and Python support.

**Comment by ressy** [comment]
For Python, following along with a [Jupyter Notebook](http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb) using our install paths succeeds until trying to instatiate `caffe.io.Transformer` under section 2.  The error is 

```
>>> transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ad/eng/opt/64/caffe-rc3/python/caffe/pycaffe.py", line 28, in _Net_blobs
    return OrderedDict(zip(self._blob_names, self._blobs))
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<caffe::Blob<float> >
```

Not sure yet how the problem relates to Boost, Caffe, and Python; possibly it's related to Boost's python bindings (?)

**Comment by ressy** [comment]
Boost.Python documentation: http://www.boost.org/doc/libs/1_60_0/libs/python/doc/html/index.html

**Comment by ressy** [comment]
Boost.Python seems OK since an example module compiles and imports fine.

**Comment by ressy** [comment]
It's a bug fixed in the latest Caffe code.  See eng-it/linux-builds#1

**Comment by ressy** [comment]
Latest build allows Python integration to work correctly via Boost.  Next just finish scripting the basic examples.
